/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Naruto Sage Mode
*/
"use client";
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

const Naruto = React.memo(function Naruto(props) {
    const modelRef = useRef();
    const { nodes, materials, animations } = useGLTF('/models/naruto.glb')
    const { actions } = useAnimations(animations, modelRef)

    useFrame((state) => {
        modelRef.current.position.y =
            -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    });

    return (
        <group ref={modelRef} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={249.231}>
                    <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Object_4">
                                    <primitive object={nodes._rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials['nr2_tex01.pngmat']}
                                        skeleton={nodes.Object_7.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_8"
                                        geometry={nodes.Object_8.geometry}
                                        material={materials['nr2_tex02.pngmat']}
                                        skeleton={nodes.Object_8.skeleton}
                                    />
                                    <skinnedMesh
                                        name="Object_9"
                                        geometry={nodes.Object_9.geometry}
                                        material={materials['nr2_eye.pngmat']}
                                        skeleton={nodes.Object_9.skeleton}
                                    />
                                    <group name="Object_6" />
                                    <group name="mesh18" />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
});

export default Naruto;
useGLTF.preload('/models/naruto.glb')

